django-app/api/urls.py
from api.models import CategoryResource, CourseRecourse
from tastypie.api import Api
from django.urls import path, include


# api/v1/categories
# api/v1/courses

api = Api(api_name='v1')
api.register(CategoryResource())
api.register(CourseRecourse())

urlpatterns = [
    path('', include(api.urls), name='index')
]

django-app/base/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    # path('shop/', include('shop.urls')),
    path('api/', include('api.urls')),
]

django-app/shop/urls.py
# from django.contrib import admin
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/<int:course_id>', views.single_course, name='single_course'),
    path('course/<int:course_id>/edit', views.single_course_edit, name='single_course_edit'),
]

django-app/api/models.py
from tastypie.resources import ModelResource
from shop.models import Category, Course
from tastypie.authorization import Authorization
from .authentication import CustomAuth


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseRecourse(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'delete']
        excludes = ['created_at', 'reviews_qty']
        authentication = CustomAuth()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category'] = bundle.obj.category
        return bundle

django-app/shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

django-app/shop/forms.py
from django import forms

class ContactForm(forms.Form):
    title = forms.CharField(max_length=255)
    # email = forms.EmailField()
    # message = forms.CharField(widget=forms.Textarea)

django-app/shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Course
from .forms import ContactForm


# !!!! CONTROLLER FILE


def index(request):
    courses = Course.objects.all()
    return render(request, 'shop/courses.html', {'courses': courses})


def single_course(request, course_id):
    # Option 1
    # try:
    #     course = Course.objects.get(pk=course_id)
    #     return render(request, 'shop/single-course.html',  {'course': course})
    # except Course.DoesNotExist:
    #     raise Http404()
    
    # Option 2
    course = get_object_or_404(Course, pk=course_id)
    return render(request, 'shop/single-course.html',  {'course': course})

def single_course_edit(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # Process the form data
            title = form.cleaned_data[course.title]
            # email = form.cleaned_data['email']
            # message = form.cleaned_data['message']
            # ...
    else:
        form = ContactForm()
    return render(request, 'shop/single-course-edit.html',  {'course': course, 'form': form})

django-app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %} {% endblock %} </title>

</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
            <a href={% url "shop:index" %} class="navbar-brand">Courses shop</a>
            <span>
                <a href="/admin/" class='me-2' target="_blank">Admin</a>
                <a href="/api/v1/" target="_blank">Api</a>
                <a href="/login/">Sign up</a>
            </span>
        </div>
    </nav>
    <main class="container">
        {% block courses %}
        {% endblock %}
        {% block course %}
        {% endblock %}
    </main>
    
</body>
</html>

django-app/templates/shop/courses.html
{% extends "base.html" %} {% block title %}All
courses{% endblock %} {% block courses %}

<table
  class="table mt-5 table-bordered table-striped table-hover"
>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Price</th>
      <th>Students qty</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for course in courses %}
    <tr>
      <td><a href={% url "shop:single_course" course.id %}>{{ course.title }}</a></td>
      <td>{{ course.category }}</td>
      <td>{{ course.price }}</td>
      <td>{{ course.students_qty }}</td>
      <td>
        <a href={% url "shop:single_course_edit" course.id %}>
          Edit
        </a>
        <button class="btn btn-primary">
          Buy
        </button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

django-app/templates/shop/single-course-edit.html
{% extends "base.html" %} {% block title %}{%
    course.title %}{% endblock %} {% block course %}
    1111
    <form method="post" action="{% url "shop:single_course_edit" course.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
    {% endblock %}

django-app/templates/shop/single-course.html
{% extends "base.html" %} {% block title %}{%
course.title %}{% endblock %} {% block course %}
<div class="card mt-5">
  <div class="card-body">
    <h1 class="">{{ course.title }}</h1>
    <h2>{{ course.category }}</h2>
    <p>Price: {{ course.price }}</p>
    <p>
      Student quantity: {{ course.students_qty }}
    </p>
    <button class="btn btn-primary">Buy</button>
  </div>
</div>

{% endblock %}